### ISSUE TITLE
index.html CSS

### ISSUE THREAD

**Issue by AltoHearts** [alejandroch495/YearUpShowcase#5]
now that the index.html has content, it needs CSS styling

**Comment by alejandroch495** [comment]
I will get right on this issue. EZ

**Comment by alejandroch495** [comment]
Update in 3

**Comment by alejandroch495** [comment]
We got a problem. My 24+ hours worth of work just got fricked and I now I want to commit the die.

**Comment by alejandroch495** [comment]
Done
